version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: finconecta-postgres
    restart: always
    environment:
      POSTGRES_USER: finconecta_user
      POSTGRES_PASSWORD: finconecta_pass
      POSTGRES_DB: finconecta_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
