services:
  postgres-db:
    image: postgres:latest
    container_name: finconecta-postgres
    restart: always
    environment:
      POSTGRES_USER: finconecta_user
      POSTGRES_PASSWORD: finconecta_pass
      POSTGRES_DB: finconecta_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finconecta-net

  mongo-db:
    image: mongo:latest
    container_name: finconecta-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - finconecta-net

networks:
  finconecta-net:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
