server:
  port: ${SERVER_PORT:8080}

spring:
  # ------------------------------------
  # Configuración de Base de Datos PostgreSQL
  # ------------------------------------
  datasource:
    url: jdbc:postgresql://localhost:5432/finconecta_db
    username: finconecta_user
    password: finconecta_pass
    driver-class-name: org.postgresql.Driver

  # ------------------------------------
  # Configuración de JPA / Hibernate
  # ------------------------------------
  jpa:
    # CRÍTICO: Indica a Spring que use Hibernate y cómo gestionar el esquema.
    hibernate:
      ddl-auto: update # Crea/actualiza tablas automáticamente.
    show-sql: true     # Imprime el SQL generado.
    properties:
      hibernate:
        format_sql: true # Formatea el SQL para que sea legible.

# ------------------------------------
# 2. Configuración de JWT
# ------------------------------------
app:
  jwt:
    # Valor del secreto (debe ser el mismo que usaste antes)
    secret: 791d8dbe27e033f48ac3c4344e12acc352174420432c5b0da57e90e402efb2ef
    # Tiempo de expiración del token en milisegundos (24 horas)
    expiration-ms: 86400000

# ------------------------------------
# 3. Configuración CORS
# ------------------------------------
cors:
  allowed-origins: http://localhost:3000,http://127.0.0.1:3000
